<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260820111507 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE parts_list (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, number VARCHAR(255) NOT NULL, cost NUMERIC(18, 2) NOT NULL, count INT NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, order_number_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FAF01AAD8C26A5E8 ON parts_list (order_number_id)');
        $this->addSql('CREATE TABLE works_list (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, cost NUMERIC(18, 2) NOT NULL, time INT NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, order_number_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_417836618C26A5E8 ON works_list (order_number_id)');
        $this->addSql('ALTER TABLE parts_list ADD CONSTRAINT FK_FAF01AAD8C26A5E8 FOREIGN KEY (order_number_id) REFERENCES "order" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE works_list ADD CONSTRAINT FK_417836618C26A5E8 FOREIGN KEY (order_number_id) REFERENCES "order" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "order" DROP works_list');
        $this->addSql('ALTER TABLE "order" DROP parts_list');
        $this->addSql('ALTER TABLE "order" ALTER payment TYPE NUMERIC(18, 2)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE parts_list DROP CONSTRAINT FK_FAF01AAD8C26A5E8');
        $this->addSql('ALTER TABLE works_list DROP CONSTRAINT FK_417836618C26A5E8');
        $this->addSql('DROP TABLE parts_list');
        $this->addSql('DROP TABLE works_list');
        $this->addSql('ALTER TABLE "order" ADD works_list JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE "order" ADD parts_list JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE "order" ALTER payment TYPE DOUBLE PRECISION');
    }
}
